cultuurnet/uitpas-beheer-angular

app/styles/components/_layout.scss
app/styles/components/_login.scss
app/styles/components/_main.scss
app/styles/components/_sidebar.scss
app/styles/core/_variables.scss

Links bij titels in sidebar worden niet naar rechts gepulled, pull-left & pull-right added to main, fix mobile screen margin welcome-screen, fix layout scrollable main content, fixed sidebar, fixed header

Misc. style fixes

---

app/scripts/controllers/activity.controller.js
app/scripts/factories/activity.factory.js
app/scripts/services/activity.service.js
app/views/modal-passholder-activity-tariffs.html
app/views/modal-passholder-memberships.html
test/spec/factories/activity.factory.js
test/spec/services/activity.service.js

Hide tariffs without available coupons.

UBR-273: include coupon code selling tickets

---

app/index.html
app/scripts/app.js
app/scripts/controllers/passholderSearch.js
app/scripts/group/ubr.group.module.js
app/scripts/services/uitpas-router.service.js
app/views/sidebar-passholder-search.html
test/spec/controllers/passholderSearch.js
test/spec/services/uitpas-router.service.js

This router service can be used to go directly to an UiTPAS identifier. It can also listen to scanned passes and redirect automatically.

UBR-218: UiTPAS Router

---

app/views/activity/content-passholder-activities.html

so you can search through activities when pressed enter.

UBR-220 added form tag on activity search

---

app/views/passholder/sidebar-passholder-details.html

UBR-282: hide the links to alter the kansenstatuut for unauthorised counters

---

app/scripts/counter/statistics/counter-statistics.controller.js
app/styles/components/_statistics.scss

- Changed order of graph components to the following: Period 1 area, period 2 area, period 1 lines, period 1 dots, period 2 lines, period 2 dots.
- Tweaked layout of statistics above the table to line up with the graph.

Feedback on UPS-2063

---

app/scripts/counter/statistics/counter-statistics.controller.js
app/views/counter-statistics/statistics-general-table.html

Fix 2 help texts appearing in tooltips when hovering table heading.

UPS-1990: Fix regression with help texts.

---

app/views/counter-statistics/statistics-exchanges.html

see Request https://jira.uitdatabank.be/browse/UPS-2214

Changed displaying order

---

app/scripts/registration/registration-modal.controller.js
app/scripts/utilities/datavalidation.service.js

feature/UPS-2710: Stop "validating" after a response was received

---

app/views/registration/content-passholder-register.html

feature/UPS-2730: Fixed copy "Pashouder registreren"

---

app/scripts/activity/activity.controller.js
app/views/activity/content-activities.html

feature/UPS-2668: Claim tariff bulk action

---

app/scripts/counter/membership/create-membership-modal.controller.js

feature/UPS-2498: Foute foutmelding als medewerker / beheerder al toegevoegd is aan een balie via browser

---

app/scripts/passholder/detail.controller.js
app/scripts/passholder/ubr.passholder.module.js
app/scripts/registration/ubr.registration.module.js
test/spec/passholder/detail.controller.spec.js

feature/UPS-2040: Set destination param when registering a new passholder

---

app/scripts/passholder/replace-pass-controller.js
test/spec/passholder/replace-pass..controller.spec.js

change replace pass REMOVE reason to DEFECT
**WIP:** needs Silex changes before merging

WIP: UPS - 3074

---

.jshintrc
app/index.html
app/scripts/app.js
bower.json
test/.jshintrc
test/karma.conf.js

Add Sentry configuration

---

Gruntfile.js
app/index.html
config.dist.json
package-lock.json
package.json

Add Sentry environment at build time

---

app/scripts/membership/membership-register.controller.js
app/views/membership/modal-passholder-membership-registration.html

Show error in membership registration

---

app/scripts/activity/activity.controller.js

Sort activities ASC when no or custom date range is selected

---

.gitignore
package.json

- Added `bower` as a dev dependency
- Added `npm` scripts to run `bower` and `grunt build`

Add npm scripts

---

app/scripts/registration/voucher-number.directive.js

Clear all errors when valid voucher number is received

---

app/index.html
app/scripts/counter/expense-report/expense-report.controller.js
app/scripts/counter/expense-report/expense-report.service.js
app/views/expense-report/generate-report.html
test/spec/counter/expense-report/expense-report.controller.spec.js

Expense reports

---

app/index.html
app/scripts/polyfills.js

Add polyfill to support Array.find

---

.jshintrc
app/index.html
app/scripts/app.js
app/scripts/initSentry.js
bower.json
config.dist.json
test/.jshintrc
test/karma.conf.js

Add Sentry

---

app/scripts/activity/activity.controller.js
test/spec/activity/activity.controller.spec.js

Always explicitly sort activities by availableto

---

app/scripts/counter/activities/activities.controller.js

Filter activities by the next 30 days by default

---

app/scripts/app.js
app/scripts/counter/activities/activities.controller.js

Correctly parse activity dates

---

app/index.html
app/scripts/utilities/tooltip.directive.js
app/views/passholder/bulk-actions/sidebar-selected-passholders.html

Not all card systems are displayed in sidebar

---

Gruntfile.js

Add sourcemap files to build

---

app/scripts/app.js
app/scripts/counter/counters.controller.js
app/scripts/counter/ubr.counter.module.js
app/scripts/utilities/app.controller.js

UPS-3713: Redirect to requested path after login

---

app/scripts/registration/passholder-register.controller.js

Change the default enddate of kansentarief to year+1

change default kansentarief date to year+1

---

app/views/passholder/modal-passholder-ticket-sales.html

Aangepast: tekst bij historiek
https://jira.uitdatabank.be/browse/UPS-4500

Update tekst historiek modal-passholder-ticket-sales.html

---

app/views/passholder/modal-passholder-ticket-sales.html

Reverts, as this change was needed on reward and not on ticket-sales

Revert "Update tekst historiek modal-passholder-ticket-sales.html"

---

app/views/passholder/modal-passholder-checkins.html

Aangepast
https://jira.uitdatabank.be/browse/UPS-4500
Update historiek pashouder modal-passholder-checkins.html

Update historiek pashouder modal-passholder-checkins.html

---

app/views/login.html

UPS-4674 - remove link to scholen application

UPS-4674 - remove link to scholen application on login page

---

app/scripts/registration/registration-modal.controller.js
app/views/registration/contact-data-step.html
app/views/registration/opt-ins-data-step.html

https://jira.publiq.be/browse/UPS-4769

[UPS-4769] Feat: changes for registration of -16

---

app/views/group/activities.html

UPS-4836 - clarify message when passholder does not have discounts

UPS-4836 - clarify message when passholder does not have discounts

---

app/scripts/passholder/search/results-viewer.controller.js
app/views/passholder/search/result-viewer.html

Reverts cultuurnet/uitpas-beheer-angular#385

Revert "UPS-5207 - improve logic of active kansenstatuut check on bulk search…"

---

app/views/help/sidebar-help.html

Ticket: https://jira.publiq.be/browse/UPS-5050
Fix the link to the manual, plus the status of systems.

UPS-5050 - Fix link to manual + Status of system

---

app/scripts/help/help.controller.js
app/views/help/sidebar-help.html

JS changes to fix the external link UPS-5050
ticket: https://jira.publiq.be/browse/UPS-5050

UPS-5050 - fix external link

---

app/index.html
app/scripts/utilities/mobile-banner.directive.js
app/styles/components/_layout.scss
app/styles/components/_main.scss
app/styles/components/_mobile-banner.scss
app/styles/components/_navbar.scss
app/styles/components/_sidebar.scss

Added a banner for mobile and tablet devices, so that they could be redirected to the new mobile balie app.
Refs: [#UPS-5329](https://jira.publiq.be/browse/UPS-5329)

feat: mobile banner
